#!/usr/bin/env php
<?php

/*
 * --------------------------------------------------------------------
 * Webby command-line tools
 * --------------------------------------------------------------------
 * The main entry point into the CLI system and allows you to run
 * commands and perform maintenance on your application.
 *
 * Because Webby can handle CLI requests as just another web request
 * this class mainly acts as a passthru to the framework itself.
 */

// Define Console Application Version
define('WEBBY_CLI_VERSION', 'v0.8.0');

// Define Webby Rootpath
define('WEBBY_ROOTPATH', __DIR__);

// Define Console Application Environment
// Use 'development', 'testing', 'production'
// Not for typos you can copy and paste the above
// and replace in the second argument below
define('ENVIRONMENT', 'development'); 

// Use Console Class
use Base\Console\Console;

// Grab argv values
$args = $_SERVER['argv'];

// Load composer
require_once __DIR__ . '/vendor/autoload.php';

/*
* --------------------------------------------------------------------
* Run Webby Cli Application
* --------------------------------------------------------------------
* 
* All commands go through Console::run()
*
*/
Console::run($args);
